apiVersion: apps/v1           # 쿠버네티스 api 버전
kind: Deployment              # 생성할 오브젝트 종류
metadata:
  name: tomcat-deployment      # deployment의 이름
  labels:
    app: tomcat              # label 지정
spec:                         # deployment의 스펙을 정의
  replicas: 1                 # 3개의 pod 설정
  selector:                   # deployment가 관리할 pod를 찾는 방법을 정의
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:                 # pod의 label
        app: tomcat
    spec:
      containers:             # 컨테이너 설정
      - name: tomcat-server
        image: bedboy92/gunhoo:centos7-tomcat9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    run: tomcat-svc
spec:
  type: NodePort     # 서비스 타입
  ports:
  #- port: 8080       # 서비스 포트
  #  targetPort: 8080   # 타켓, 즉 pod의 포트
  - port: 8009       # 서비스 포트
    targetPort: 8009   # 타켓, 즉 pod의 포트
    protocol: TCP
    name: tomcat
  selector:
    app: tomcat

