apiVersion: apps/v1           # 쿠버네티스 api 버전
kind: Deployment              # 생성할 오브젝트 종류
metadata:                
  name: httpd-admin-deployment      # deployment의 이름
  labels:
    app: httpd-admin              # label 지정
spec:                         # deployment의 스펙을 정의
  replicas: 1                 
  selector:                   # deployment가 관리할 pod를 찾는 방법을 정의
    matchLabels:     
      app: httpd-admin
  template:
    metadata:
      labels:                 # pod의 label
        app: httpd-admin
    spec:
      containers:             # 컨테이너 설정
      - name: httpd-admin-pod         
        image: bedboy92/gunhoo:centos7-httpd24
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-admin-svc
  labels:
    run: httpd-admin-svc
spec:
  type: NodePort     # 서비스 타입
  ports:
  - port: 80       # 서비스 포트
    targetPort: 80   # 타켓, 즉 pod의 포트
    protocol: TCP
    name: http
  selector:
    app: httpd-admin
