apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.6.199.104
    path: /data
